name: Build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  mirror:
    runs-on: ubuntu-latest
    # "Thank you a so much for a [letting me mirror my forks to Coderberg]!" - Legit Mario
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://codeberg.org/heathercat123/flash95.git'
          GIT_USERNAME: heathercat123
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/checkout@v3
      with:
        repository: 'itsmattkc/msvc600'
        path: msvc600

    - uses: actions/checkout@v3
      with:
        repository: 'heathercat123/winsock351'
        path: winsock351

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        # Use minimum supported version
        cmake-version: '3.13.x'

    - name: Build wrappers
      shell: cmd
      run: |
        call .\msvc600\VC98\bin\VCVARS32.BAT x86
        cd wrappers
        mkdir build
        cd build
        cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release
        cmake --build .
        mkdir ..\..\build
        move corkel32.dll ..\..\build
        move corusr.dll ..\..\build
        move crypt32.dll ..\..\build
        move corshel.dll ..\..\build
        move cornt.dll ..\..\build

    - name: Build winsock351
      shell: cmd
      run: |
        call .\msvc600\VC98\bin\VCVARS32.BAT x86
        cd winsock351
        nmake /f winsock351.mak CFG="winsock351 - Win32 Release"
        move .\Release\ws2_32.dll ..\build

    - name: Copy binaries
      shell: cmd
      run: |
        copy bin\wininet\wininet.dll build
        copy bin\msvcrt\msvcrt.dll build

    - name: Write README
      shell: cmd
      run: |
        set readme=build\_README.MD
        echo If you have Winsock 2 installed or you are on Windows NT 4, please delete ws2_32.dll! > %readme%
        echo If you have the 32-bit version of Internet Explorer 3 (included in Windows 95 OSR2) or newer installed, delete wininet.dll and urlmon.dll >> %readme%
        echo If you have the 32-bit version of Internet Explorer 5 (included Windows 98 SE and 2000) or newer installed, delete crypt32.dll >> %readme%
        echo. >> %readme%
        echo Have fun! >> %readme%
        echo    - Heathercat123 >> %readme%
        
    - name: Patch Adobe Flash
      shell: cmd
      run: |
        copy patches\flash9r289.exe build\ 

    - name: Upload Artifacts
      uses: actions/upload-artifact@master
      with:
        name: flash95
        path: |
          build/
